for pid in `ssh akane.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh akane.cs.berkeley.edu kill $pid ; done
for pid in `ssh arlet.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh arlet.cs.berkeley.edu kill $pid ; done
for pid in `ssh barry.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh barry.cs.berkeley.edu kill $pid ; done
for pid in `ssh bonza.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh bonza.cs.berkeley.edu kill $pid ; done
for pid in `ssh braeburn.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh braeburn.cs.berkeley.edu kill $pid ; done
for pid in `ssh crispin.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh crispin.cs.berkeley.edu kill $pid ; done
for pid in `ssh davey.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh davey.cs.berkeley.edu kill $pid ; done
for pid in `ssh delicious.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh delicious.cs.berkeley.edu kill $pid ; done
for pid in `ssh dulcet.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh dulcet.cs.berkeley.edu kill $pid ; done
for pid in `ssh empress.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh empress.cs.berkeley.edu kill $pid ; done
for pid in `ssh fiesta.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh fiesta.cs.berkeley.edu kill $pid ; done
for pid in `ssh firmgold.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh firmgold.cs.berkeley.edu kill $pid ; done
for pid in `ssh freyburg.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh freyburg.cs.berkeley.edu kill $pid ; done
for pid in `ssh fuji.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh fuji.cs.berkeley.edu kill $pid ; done
for pid in `ssh geneva.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh geneva.cs.berkeley.edu kill $pid ; done
for pid in `ssh gilpin.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh gilpin.cs.berkeley.edu kill $pid ; done
for pid in `ssh grove.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh grove.cs.berkeley.edu kill $pid ; done
for pid in `ssh haas.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh haas.cs.berkeley.edu kill $pid ; done
for pid in `ssh hazen.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh hazen.cs.berkeley.edu kill $pid ; done
for pid in `ssh liberty.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh liberty.cs.berkeley.edu kill $pid ; done
for pid in `ssh mcintosh.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh mcintosh.cs.berkeley.edu kill $pid ; done
for pid in `ssh mio.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh mio.cs.berkeley.edu kill $pid ; done
for pid in `ssh orin.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh orin.cs.berkeley.edu kill $pid ; done
for pid in `ssh priam.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh priam.cs.berkeley.edu kill $pid ; done
for pid in `ssh shay.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh shay.cs.berkeley.edu kill $pid ; done
for pid in `ssh taylor.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh taylor.cs.berkeley.edu kill $pid ; done
for pid in `ssh vand.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh vand.cs.berkeley.edu kill $pid ; done
for pid in `ssh viking.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh viking.cs.berkeley.edu kill $pid ; done
for pid in `ssh winesap.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh winesap.cs.berkeley.edu kill $pid ; done
for pid in `ssh york.cs.berkeley.edu ps -Ao pid,command | grep java | sed "s/^[ ]*//" | cut -d\  -f1` ; do ssh york.cs.berkeley.edu kill $pid ; done

