ssh arlet.cs.berkeley.edu ls
ssh barry.cs.berkeley.edu ls
ssh bonza.cs.berkeley.edu ls
ssh braeburn.cs.berkeley.edu ls
ssh crispin.cs.berkeley.edu ls
ssh davey.cs.berkeley.edu ls
ssh delicious.cs.berkeley.edu ls
ssh dulcet.cs.berkeley.edu ls
ssh empress.cs.berkeley.edu ls
ssh fiesta.cs.berkeley.edu ls
ssh firmgold.cs.berkeley.edu ls
ssh freyburg.cs.berkeley.edu ls
ssh fuji.cs.berkeley.edu ls
ssh geneva.cs.berkeley.edu ls
ssh gilpin.cs.berkeley.edu ls
ssh grove.cs.berkeley.edu ls
ssh haas.cs.berkeley.edu ls
ssh hazen.cs.berkeley.edu ls
ssh liberty.cs.berkeley.edu ls
ssh mcintosh.cs.berkeley.edu ls
ssh mio.cs.berkeley.edu ls
ssh orin.cs.berkeley.edu ls
ssh priam.cs.berkeley.edu ls
ssh shay.cs.berkeley.edu ls
ssh taylor.cs.berkeley.edu ls
ssh vand.cs.berkeley.edu ls
ssh viking.cs.berkeley.edu ls
ssh winesap.cs.berkeley.edu ls
ssh york.cs.berkeley.edu ls