ssh icluster2.eecs.berkeley.edu echo howdy
ssh icluster3.eecs.berkeley.edu echo howdy
ssh icluster4.eecs.berkeley.edu echo howdy
ssh icluster5.eecs.berkeley.edu echo howdy
ssh icluster6.eecs.berkeley.edu echo howdy
ssh icluster7.eecs.berkeley.edu echo howdy
ssh icluster8.eecs.berkeley.edu echo howdy
ssh icluster9.eecs.berkeley.edu echo howdy
ssh icluster10.eecs.berkeley.edu echo howdy
ssh icluster11.eecs.berkeley.edu echo howdy
ssh icluster12.eecs.berkeley.edu echo howdy
ssh icluster13.eecs.berkeley.edu echo howdy
ssh icluster14.eecs.berkeley.edu echo howdy
ssh icluster15.eecs.berkeley.edu echo howdy
ssh icluster16.eecs.berkeley.edu echo howdy
ssh icluster17.eecs.berkeley.edu echo howdy
ssh icluster18.eecs.berkeley.edu echo howdy
ssh icluster20.eecs.berkeley.edu echo howdy
ssh icluster21.eecs.berkeley.edu echo howdy
ssh icluster22.eecs.berkeley.edu echo howdy
