/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.gamesman.avro;

@SuppressWarnings("all")
public class MoveValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MoveValue\",\"namespace\":\"edu.berkeley.gamesman.avro\",\"fields\":[{\"name\":\"move\",\"type\":{\"type\":\"record\",\"name\":\"MoveInfo\",\"fields\":[{\"name\":\"move\",\"type\":\"string\",\"default\":null},{\"name\":\"board\",\"type\":\"string\"}]},\"default\":null},{\"name\":\"value\",\"type\":{\"type\":\"enum\",\"name\":\"Value\",\"symbols\":[\"UNKNOWN\",\"WIN\",\"LOSE\",\"TIE\",\"DRAW\"]}},{\"name\":\"remoteness\",\"type\":\"int\"},{\"name\":\"score\",\"type\":\"float\"},{\"name\":\"mex\",\"type\":\"int\",\"default\":false}]}");
  public edu.berkeley.gamesman.avro.MoveInfo move;
  public edu.berkeley.gamesman.avro.Value value;
  public int remoteness;
  public float score;
  public int mex;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return move;
    case 1: return value;
    case 2: return remoteness;
    case 3: return score;
    case 4: return mex;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: move = (edu.berkeley.gamesman.avro.MoveInfo)value$; break;
    case 1: value = (edu.berkeley.gamesman.avro.Value)value$; break;
    case 2: remoteness = (java.lang.Integer)value$; break;
    case 3: score = (java.lang.Float)value$; break;
    case 4: mex = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
