/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.gamesman.avro;

@SuppressWarnings("all")
public class VariantSupport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"VariantSupport\",\"namespace\":\"edu.berkeley.gamesman.avro\",\"fields\":[{\"name\":\"variant\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"fields\",\"type\":{\"type\":\"record\",\"name\":\"Fields\",\"fields\":[{\"name\":\"value\",\"type\":\"boolean\",\"default\":false},{\"name\":\"remoteness\",\"type\":\"boolean\",\"default\":false},{\"name\":\"winBy\",\"type\":\"boolean\",\"default\":false},{\"name\":\"mex\",\"type\":\"boolean\",\"default\":false}]}}]}");
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> variant;
  public edu.berkeley.gamesman.avro.Fields fields;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variant;
    case 1: return fields;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variant = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 1: fields = (edu.berkeley.gamesman.avro.Fields)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
