/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.gamesman.avro;

@SuppressWarnings("all")
public class VariationInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"VariationInfo\",\"namespace\":\"edu.berkeley.gamesman.avro\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"record\",\"name\":\"VariationName\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}},{\"name\":\"supported\",\"type\":{\"type\":\"record\",\"name\":\"Fields\",\"fields\":[{\"name\":\"moves\",\"type\":\"boolean\",\"default\":true},{\"name\":\"value\",\"type\":\"boolean\",\"default\":false},{\"name\":\"winBy\",\"type\":\"boolean\",\"default\":false},{\"name\":\"remoteness\",\"type\":\"boolean\",\"default\":false},{\"name\":\"mex\",\"type\":\"boolean\",\"default\":false}]}}]}");
  public edu.berkeley.gamesman.avro.VariationName name;
  public edu.berkeley.gamesman.avro.Fields supported;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return supported;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (edu.berkeley.gamesman.avro.VariationName)value$; break;
    case 1: supported = (edu.berkeley.gamesman.avro.Fields)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
